# Generated by Django 4.2.10 on 2024-02-28 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_contact_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=150)),
                ('Subtitle', models.CharField(max_length=150)),
                ('content', models.TextField()),
                ('slug', models.SlugField()),
                ('date', models.DateField()),
                ('img', models.ImageField(upload_to='media/')),
            ],
        ),
    ]
