# Generated by Django 4.2.10 on 2024-02-28 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_posts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Posts',
            new_name='Blogs',
        ),
    ]
