# Generated by Django 4.2.10 on 2024-02-28 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_rename_posts_blogs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blogs',
            new_name='Blog',
        ),
    ]
