# Generated by Django 4.2.10 on 2024-02-28 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_blog_subtitle_alter_blog_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='Title',
            new_name='name',
        ),
    ]
