# Generated by Django 4.2.10 on 2024-02-28 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_rename_title_blog_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='name',
            new_name='title',
        ),
    ]
